# Generated by Django 5.0 on 2026-01-27 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, help_text='LINE user ID (e.g., U4af4980629...)', max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, help_text="User's display name (from LINE profile)", max_length=200, null=True)),
                ('profile_picture_url', models.URLField(blank=True, help_text="User's profile picture URL", null=True)),
                ('tags', models.JSONField(default=list, help_text="User tags for segmentation (e.g., ['vip', 'newsletter'])")),
                ('first_interaction', models.DateTimeField(auto_now_add=True, help_text='When user first interacted with bot')),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last interaction timestamp')),
                ('message_count', models.IntegerField(default=0, help_text='Total messages received from this user')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether user is still following the bot')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, help_text='Whether user has blocked the bot')),
                ('opted_out_at', models.DateTimeField(blank=True, help_text='When user opted out of messages', null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Additional custom data (e.g., preferences, purchase history)')),
            ],
            options={
                'ordering': ['-last_interaction'],
                'indexes': [models.Index(fields=['is_active', '-last_interaction'], name='social_line_is_acti_260e10_idx'), models.Index(fields=['tags'], name='social_line_tags_9c9210_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this post transaction', primary_key=True, serialize=False)),
                ('streamfield_data', models.JSONField(default=dict, help_text='Snapshot of StreamField data at publish time')),
                ('content', models.TextField(help_text='Processed content (platform-agnostic text)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('PARTIAL', 'Partially Published'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], db_index=True, default='DRAFT', max_length=20)),
                ('platforms', models.JSONField(default=list, help_text="List of target platforms: ['facebook', 'linkedin', 'line']")),
                ('facebook_post_id', models.CharField(blank=True, db_index=True, help_text='Facebook post ID (format: {page_id}_{post_id})', max_length=100, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, db_index=True, help_text='LinkedIn post URN (e.g., urn:li:share:123456)', max_length=100, null=True)),
                ('line_message_id', models.CharField(blank=True, db_index=True, help_text='LINE message ID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Actual publish timestamp (when first platform succeeded)', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='Scheduled publish time (future)', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('last_error', models.TextField(blank=True, help_text='Last error message (for debugging)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('wagtail_page', models.ForeignKey(blank=True, help_text='Source Wagtail page (if created via CMS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_transactions', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPublishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('line', 'LINE')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_url', models.URLField(blank=True, help_text='Direct link to published post', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading Media'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, help_text="Platform-specific error code (e.g., '190' for FB token error)", max_length=50, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('media_uploaded', models.BooleanField(default=False)),
                ('media_asset_urn', models.CharField(blank=True, help_text='LinkedIn asset URN after upload', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_records', to='social.posttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('line', 'LINE')], max_length=20)),
                ('account_name', models.CharField(help_text="User-friendly name (e.g., 'Company Facebook Page')", max_length=200)),
                ('facebook_page_id', models.CharField(blank=True, help_text='Facebook Page ID', max_length=100, null=True, unique=True)),
                ('linkedin_org_urn', models.CharField(blank=True, help_text='LinkedIn organization URN (urn:li:organization:123456)', max_length=200, null=True, unique=True)),
                ('line_channel_id', models.CharField(blank=True, help_text='LINE Bot Channel ID', max_length=100, null=True, unique=True)),
                ('access_token', models.TextField(help_text='OAuth access token (TODO: encrypt at rest)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (if applicable)', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Token expiration time (Facebook: 60 days)', null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, help_text='Last successful token refresh', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this credential is currently in use')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last time token was verified as valid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform', 'account_name'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='social_soci_platfor_e6820e_idx'), models.Index(fields=['token_expires_at'], name='social_soci_token_e_a4bb16_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialcredential',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('facebook_page_id__isnull', False), ('platform', 'facebook')), models.Q(('linkedin_org_urn__isnull', False), ('platform', 'linkedin')), models.Q(('line_channel_id__isnull', False), ('platform', 'line')), _connector='OR'), name='platform_specific_id_required'),
        ),
        migrations.AddIndex(
            model_name='posttransaction',
            index=models.Index(fields=['status', '-created_at'], name='social_post_status_a11262_idx'),
        ),
        migrations.AddIndex(
            model_name='posttransaction',
            index=models.Index(fields=['scheduled_for', 'status'], name='social_post_schedul_76e4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpublishrecord',
            index=models.Index(fields=['transaction', 'platform'], name='social_plat_transac_505ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpublishrecord',
            index=models.Index(fields=['status', '-created_at'], name='social_plat_status_7d38b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformpublishrecord',
            unique_together={('transaction', 'platform')},
        ),
    ]
