# Generated by Django 5.0 on 2026-01-27 03:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('post', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Post headline (max 280 chars for Twitter compatibility)', 'max_length': 280}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Main post content (will be converted to plain text for social platforms)'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional post image (will be uploaded to each platform)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Call-to-action text (e.g., 'Learn More', 'Shop Now')", 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Call-to-action URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('headline', 0), ('body', 1), ('image', 2), ('cta_text', 3), ('cta_url', 4)]], {})}, help_text='Compose your social media post content')),
                ('publish_to_facebook', models.BooleanField(default=True, help_text='Publish this post to Facebook')),
                ('publish_to_linkedin', models.BooleanField(default=True, help_text='Publish this post to LinkedIn')),
                ('publish_to_line', models.BooleanField(default=False, help_text='Send this post to LINE followers')),
                ('scheduled_publish_time', models.DateTimeField(blank=True, help_text='Schedule this post for future publishing (leave blank for immediate)', null=True)),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
            },
            bases=('wagtailcore.page',),
        ),
    ]
